# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9b5f35fc7c1216437767c68b3fe4c81f4736eca38fbaf5ec6e0a696b8b43e92795ab98130cef752d1a85cb6bb2e158d1176339a87a96e3c42d217a06123cf560

test:
  secret_key_base: 2f96ce9b8526c1fc5340dc9b1d61ad4483c5b2760cb482446d2397ab303df68fe135b3fadd95da4963af5ce0154a5697635c6a1da36d47a1917b869d1fa9b874

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
